services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - ./linux/logrotate.d/app:/etc/logrotate.d/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "go run cmd/main.go"
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: sh -c "npm run build && npm run start"
    restart: always

#  db:
#    image: postgres:16.1
#    environment:
#      POSTGRES_DB: sample
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    volumes:
#      - ./data:/var/lib/postgresql/data 