services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - ./api/linux/logrotate.d/app:/etc/logrotate.d/app
    working_dir: /app
    tty: true
    command: sh -c "go run cmd/main.go"
    restart: always

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: sh -c "npm run build && npm run start"
    restart: always
