services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - GENIE_ENV=dev
      - ACCESS_TOKEN_SECRET=randomstring
      - ACCESS_TOKEN_EXPIRES_SECONDS=900
      - REFRESH_TOKEN_SECRET=randomstring
      - REFRESH_TOKEN_EXPIRES_SECONDS=86400
      - COOKIE_ACCESS_SECURE=false
      - COOKIE_REFRESH_SECURE=false
      - COOKIE_ACCESS_HTTPONLY=true
      - COOKIE_REFRESH_HTTPONLY=true
      - FRONTEND_ORIGIN=http://localhost:3000
    working_dir: /app
    command: [ "./entrypoint.sh" ]
    tty: true

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=http://api:8000
      - NEXT_PUBLIC_API_HOST=http://localhost:8000
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    tty: true

  db:
    image: postgres:17.4
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
