services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/app
      - ./api/linux/logrotate.d/app:/etc/logrotate.d/app
    ports:
      - "8000:8000"
    environment:
      - GENIE_ENV=prod
    working_dir: /app
    command: ["./api/entrypoint.sh"]
    tty: true

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: sh -c "npm run build && npm run start"
    restart: always