services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=project_db
      - JWT_EXPIRATION=2592000
      - JWT_SECRET=secret
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    tty: true

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_HOST=http://api:8000
      - NEXT_PUBLIC_API_HOST=http://localhost:8000
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    tty: true

  db:
    image: postgres:17.4
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres