services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: sh -c "npm run start"
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    working_dir: /app
    command: sh -c "npm run build && npm run start"
    restart: always